CREATE TABLE Clubs (
	Clubs_Id SERIAL PRIMARY KEY,
	Clubs_Nom VARCHAR(50) NOT NULL,
        Clubs_NomCourt VARCHAR(5) NOT NULL,
        Clubs_Pays VARCHAR(50) NOT NULL
	
);


CREATE TABLE Joueurs (
	Jr_Id SERIAL PRIMARY KEY ,
	Jr_Nom VARCHAR(50) NOT NULL,
	Jr_Prenom VARCHAR(50) NOT NULL,
	Jr_Naissance DATE,
        Jr_Post VARCHAR(50) NOT NULL,
        Jr_Nationalité VARCHAR(50) NOT NULL

);
CREATE TABLE Carriere(
	Ca_id SERIAL,
	Jr_Id INT NOT NULL,
        Clubs_Id INT NOT NULL,
        Début INT CHECK(Début > 1900),
        Fin INT  CHECK(Fin <=2020), 
	FOREIGN KEY (Clubs_Id) REFERENCES Clubs(Clubs_Id),
	FOREIGN KEY (Jr_Id) REFERENCES Joueurs(Jr_Id),
	PRIMARY KEY (Jr_Id, Clubs_id)
        
);

INSERT INTO Joueurs (Jr_Nom, Jr_Prenom, Jr_Naissance, Jr_Post, Jr_Nationalité) VALUES
                     ('Zidane', 'Zinédine', '1972-06-23' ,  'MC','Français'),
                     ('Ronaldo','Cristiano','1985-02-05' ,  'BU','Potugais'),
                     ('Messi','Lionel','1987-06-24',  'AD','Argentin'),
                     ('Benzema','Karim','1987-12-19', 'AC' ,'Français'),
                     ('Griezmann','Antoine','1991-03-21','BU', 'Français'),
                     ('Mbappé','Kylian','1998-12-20',  'BU','Français'),
                     ('Rashford','Marcus','1997-10-03',  'MG','Britannique'),
                     ('Neymar','junior','1992-03-05', 'AG', 'Brésilien'),
                     ('Mahrez','Riyad','1991-02-21',  'AD','Français'),
                     ('ZIYECH','HAKIM','1993-03-19' ,  'MOC','Néerlandais et Marocain'),
                     ('Dembélé','Ousmane','1997-05-15',  'AD','FRANCAIS'),
                     ('MOUNT','Mason','1999-01-10',  'AC' ,'Français'),
                     ('Havertz','Kai','1999-06-11', 'MOC','Allemand'),
                     ('Becker','Alisson','1992-10-02','GK', 'Brésilien'),
                     ('Neuer','Manuel','1986-03-27',  'GK','Allemand'),	
                     ('Davies','Alphonso','2000-05-25', 'DG','Canadienne'),	
                     ('Carvajal','Dani','1992-01-11',  'DD','Espagne'),	
                     ('Pavard','Benjamin','1996-10-12', 'DD','Français'),	
                     ('Arnold','Trent-Alexandre','1998-10-07',  'DD','Britannique'),	
                     ('Robertson','Andrew','1994-03-11',  'DG','Ecosse'),	                    
                     ('Ramos','Sergio','1986-03-30', 'DC','Espagne'),	
                     ('Kimich','Joshua','1995-02-08',  'MDC','Allemand'),	
                     ('De Bruyne','Kevin','1991-06-28', 'MOC','Belge'),	
                     ('Goretzka','Leon','1995-02-06','MC','Allemand'),
                     ('Mané','Sadio','1992-04-10', 'AG','Sénégalais');						 

INSERT INTO Clubs (Clubs_Nom, Clubs_NomCourt, Clubs_Pays) VALUES
                  ('Real madrid CF','RMA','Espagne'),
                  ('FC Barcelona','BAR','Espagne'),
                  ('Atlético de Madrid','ATH','Espagne'),
                  ('Real Sociedad','RS','Espagne'),
                  ('Manchester United', 'MU','Angleterre'),
                  ('Leicester City','LEI','Angleterre'),
                  ('Manchester City', 'MC','Angleterre'),
                  ('juventus','JUV','Italie'),
                  ('Monaco','MON','france'),
                  ('Paris-saint-Germain', 'PSG','France'),
                  ('Olympique Lyonnais','OL','France'),
                  ('Olympique de Marseille','OM','France'),
                  ('Cannes','CAN','France'),
                  ('Bordeaux','BOR','France'),
                  ('Le havre AC','HAC','France'),
                  ('Santos FC','SAN','Brésil'),
                  ('Sporting CP', 'SPO','Portugal'),		  
	          ('FC Metz', 'FCM', 'France'),
                  ('Red Bull Salzbourg','RBS', 'Autriche'),
 	          ('Southhampton','SFC', 'Portugal'),
	          ('Liverpool','LFC', 'angleterre'),	  
	          ('AJAX Amsterdam','AJA', 'Pays Bas'),
	          ('Chelsea Fc', 'CFC', 'angleterre'),
	          ('FC Twenty', 'FCT', 'Pays Bas'),
	          ('FC HERRNEVEEN', 'FCH', 'Pays Bas'),	  
		  ('Stade rennais FC', 'RFC', 'France'),
		  ('Bourussia Dortmund', 'BVB', 'Allemagne'),		  
	          ('Bayern Leverkusen', 'BL', 'Allemagne'),		  
	          ('SC International', 'SCI', 'Brésil'),
                  ('As Rome', 'ASM', 'Italie'),
		  ('Shalke', 'SH', 'Allemagne'),
		  ('Bayren Munich', 'FCB', 'Allemagne'),
		  ('Vancouver WhiteCaps', 'VWC', 'Canada'),
	          ('Losc Lille', 'LSL', 'France'),
	          ('VFB Stuttgart', 'VFB', 'Allemagne'),
	          ('Hull City AFC', 'HAf', 'Angleterre'),
	          ('Seville FC', 'SVF', 'Espagne'),
	          ('Rb Leibzig', 'RBL', 'Allemagne'),
                  ('VFL Wolfsburg', 'VFL', 'Portugal'),
	          ('VFL Bochum', 'VLB', 'Allemagne');
                 
				
				  
				  
				  


INSERT INTO Carriere (Jr_Id, Clubs_Id, début, Fin) VALUES
   
 
   ((SELECT Jr_Id FROM Joueurs WHERE Jr_Nom = 'Zidane'),8,1996,2001),
   ((SELECT Jr_Id FROM Joueurs WHERE Jr_Nom = 'Zidane'),1,2001,2006),
   ((SELECT Jr_Id FROM Joueurs WHERE Jr_Nom = 'Zidane'),14,1992,1996),
   ((SELECT Jr_Id FROM Joueurs WHERE Jr_Nom = 'Zidane'),13,1987,1992),
   ((SELECT Jr_Id FROM Joueurs WHERE Jr_Nom = 'Ronaldo'),8,2018,2020),
   ((SELECT Jr_Id FROM Joueurs WHERE Jr_Nom = 'Ronaldo'),1,2009,2018),
   ((SELECT Jr_Id FROM Joueurs WHERE Jr_Nom = 'Ronaldo'),5,2003,2009),
   ((SELECT Jr_Id FROM Joueurs WHERE Jr_Nom = 'Ronaldo'),17,1997,2003),
   ((SELECT Jr_Id FROM Joueurs WHERE Jr_Nom = 'Messi'),2,2003,2020),
   ((SELECT Jr_Id FROM Joueurs WHERE Jr_Nom = 'Benzema'),1,2009,2020),
   ((SELECT Jr_Id FROM Joueurs WHERE Jr_Nom = 'Benzema'),11,2004,2009),
   ((SELECT Jr_Id FROM Joueurs WHERE Jr_Nom = 'Griezmann'),2,2019,2020),
   ((SELECT Jr_Id FROM Joueurs WHERE Jr_Nom = 'Griezmann'),3,2019,2020),
   ((SELECT Jr_Id FROM Joueurs WHERE Jr_Nom = 'Griezmann'),4,2009,2014),
   ((SELECT Jr_Id FROM Joueurs WHERE Jr_Nom = 'Mbappé'),10,2017,2020),
   ((SELECT Jr_Id FROM Joueurs WHERE Jr_Nom = 'Mbappé'),9,2015,2017),
   ((SELECT Jr_Id FROM Joueurs WHERE Jr_Nom = 'Rashford'),5,2015,2020),
   ((SELECT Jr_Id FROM Joueurs WHERE Jr_Nom = 'Neymar'),10,2017,2020),
   ((SELECT Jr_Id FROM Joueurs WHERE Jr_Nom = 'Neymar'),2,2013,2017),
   ((SELECT Jr_Id FROM Joueurs WHERE Jr_Nom = 'Neymar'),16,2009,2013),
   ((SELECT Jr_Id FROM Joueurs WHERE Jr_Nom = 'Mahrez'),7,2018,2020),  
   ((SELECT Jr_Id FROM Joueurs WHERE Jr_Nom = 'Mahrez'),6,2014,2018), 
   ((SELECT Jr_Id FROM Joueurs WHERE Jr_Nom = 'Mahrez'),15,2010,2014),
   ((SELECT Jr_Id FROM Joueurs WHERE Jr_Nom = 'ZIYECH'),23,2020,2020),  
   ((SELECT Jr_Id FROM Joueurs WHERE Jr_Nom = 'ZIYECH'),22,2016,2020),       
   ((SELECT Jr_Id FROM Joueurs WHERE Jr_Nom = 'ZIYECH'),24,2014,2016),   
   ((SELECT Jr_Id FROM Joueurs WHERE Jr_Nom = 'ZIYECH'),25,2012,2014), 
   ((SELECT Jr_Id FROM Joueurs WHERE Jr_Nom = 'Dembélé'),2,2017,2020), 
   ((SELECT Jr_Id FROM Joueurs WHERE Jr_Nom = 'Dembélé'),27,2016,2017),
   ((SELECT Jr_Id FROM Joueurs WHERE Jr_Nom = 'Dembélé'),26,2015,2016),   
   ((SELECT Jr_Id FROM Joueurs WHERE Jr_Nom = 'MOUNT'),23,2017,2020),
   ((SELECT Jr_Id FROM Joueurs WHERE Jr_Nom = 'Havertz'),23,2020,2020),   
   ((SELECT Jr_Id FROM Joueurs WHERE Jr_Nom = 'Havertz'),28,2016,2020),   
   ((SELECT Jr_Id FROM Joueurs WHERE Jr_Nom = 'Becker'),21,2018,2020),
   ((SELECT Jr_Id FROM Joueurs WHERE Jr_Nom = 'Becker'),30,2016,2018),
   ((SELECT Jr_Id FROM Joueurs WHERE Jr_Nom = 'Becker'),29,2013,2016),   
   ((SELECT Jr_Id FROM Joueurs WHERE Jr_Nom = 'Neuer'),32,2011,2020),    
   ((SELECT Jr_Id FROM Joueurs WHERE Jr_Nom = 'Neuer'),31,2006,2011),   
   ((SELECT Jr_Id FROM Joueurs WHERE Jr_Nom = 'Davies'),32,2019,2020),    
   ((SELECT Jr_Id FROM Joueurs WHERE Jr_Nom = 'Davies'),33,2016,2018),
   ((SELECT Jr_Id FROM Joueurs WHERE Jr_Nom = 'Carvajal'),1,2019,2020), 
   ((SELECT Jr_Id FROM Joueurs WHERE Jr_Nom = 'Carvajal'),28,2019,2020),
   ((SELECT Jr_Id FROM Joueurs WHERE Jr_Nom = 'Pavard'),32,2019,2020),
   ((SELECT Jr_Id FROM Joueurs WHERE Jr_Nom = 'Pavard'),35,2016,2019), 
   ((SELECT Jr_Id FROM Joueurs WHERE Jr_Nom = 'Pavard'),34,2015,2016),    
   ((SELECT Jr_Id FROM Joueurs WHERE Jr_Nom = 'Arnold'),21,2016,2020),
   ((SELECT Jr_Id FROM Joueurs WHERE Jr_Nom = 'Robertson'),21,2017,2020), 
   ((SELECT Jr_Id FROM Joueurs WHERE Jr_Nom = 'Robertson'),36,2014,2017),
   ((SELECT Jr_Id FROM Joueurs WHERE Jr_Nom = 'Ramos'),1,2005,2020), 
   ((SELECT Jr_Id FROM Joueurs WHERE Jr_Nom = 'Ramos'),37,2004,2005), 
   ((SELECT Jr_Id FROM Joueurs WHERE Jr_Nom = 'Kimich'),32,2015,2020),
   ((SELECT Jr_Id FROM Joueurs WHERE Jr_Nom = 'Kimich'),38,2013,2015),    
   ((SELECT Jr_Id FROM Joueurs WHERE Jr_Nom = 'De Bruyne'),7,2015,2020),
   ((SELECT Jr_Id FROM Joueurs WHERE Jr_Nom = 'De Bruyne'),39,2014,2015),                        				  
   ((SELECT Jr_Id FROM Joueurs WHERE Jr_Nom = 'Goretzka'),32,2018,2020),
   ((SELECT Jr_Id FROM Joueurs WHERE Jr_Nom = 'Goretzka'),31,2013,2018),   
   ((SELECT Jr_Id FROM Joueurs WHERE Jr_Nom = 'Goretzka'),40,2012,2013),   
   ((SELECT Jr_Id FROM Joueurs WHERE Jr_Nom = 'Mané'),21,2016,2020),  
   ((SELECT Jr_Id FROM Joueurs WHERE Jr_Nom = 'Mané'),19,2012,2014),   
   ((SELECT Jr_Id FROM Joueurs WHERE Jr_Nom = 'Mané'),20,2014,2016), 
   ((SELECT Jr_Id FROM Joueurs WHERE Jr_Nom = 'Mané'),18,2011,2012);      

